version: '3.8'
services:
  db:
    image: postgres:16
    container_name: rust-auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devanshu
    ports:
      - "5432:5432"
    volumes:
      - rust-auth-data:/var/lib/postgresql/data
      - .:/app
  
volumes:
    rust-auth-data: